@baseUrl = http://localhost:3000
@apiUrl = {{baseUrl}}/api/v1

# GET REQUEST
GET {{baseUrl}}

###
POST {{apiUrl}}/auth
Content-Type: application/json

{
    "username": "dented1",
    "email": "dented12@gmail.com",
    "password": "1234"
}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "dented12@gmail.com",
    "password": "1234"
}

###
POST {{apiUrl}}/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbnRlZDEyQGdtYWlsLmNvbSIsImlhdCI6MTc1MjQ2NDQ1NywiZXhwIjoxNzUyNTUwODU3fQ.xHrTemb54mjMyGUAjqoyZxOSS2MfbDGZFapLK2HELx4

{
    "type": "income",
    "date": "07-14-2025",
    "description": "Salary",
    "amount": "1000"
}